# Generated by Django 5.0.2 on 2024-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
