# Generated by Django 5.0.2 on 2024-09-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_record_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sequence',
        ),
    ]
